"""Add cleaned_content and chunks to Transcript

Revision ID: 47dd90e1ba20
Revises: 0fcf6c8583c8
Create Date: 2026-05-23 17:15:35.932687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47dd90e1ba20'
down_revision: Union[str, None] = '0fcf6c8583c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('cleaned_content', sa.Text(), nullable=True))
    op.add_column('transcripts', sa.Column('chunks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('transcripts', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transcripts', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('transcripts', 'chunks')
    op.drop_column('transcripts', 'cleaned_content')
    # ### end Alembic commands ###
