"""add_page_count_to_task_files

Revision ID: 5d5d3750653f
Revises: 6972cc05678d
Create Date: 2026-05-31 20:36:16.446694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d5d3750653f'
down_revision: Union[str, None] = '6972cc05678d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_files', sa.Column('page_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_files', 'page_count')
    # ### end Alembic commands ###
