"""add_parent_id_and_corrected_chunks_to_ai_documents

Revision ID: 6972cc05678d
Revises: d7331c44bcf9
Create Date: 2026-05-31 19:42:15.012621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6972cc05678d'
down_revision: Union[str, None] = 'd7331c44bcf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_documents', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.add_column('ai_documents', sa.Column('corrected_chunks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(None, 'ai_documents', 'ai_documents', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_documents', type_='foreignkey')
    op.drop_column('ai_documents', 'corrected_chunks')
    op.drop_column('ai_documents', 'parent_id')
    # ### end Alembic commands ###
