"""add_performance_indexes

Revision ID: c481f8f17fde
Revises: 78a699ac423d
Create Date: 2026-07-06 12:10:48.260349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c481f8f17fde'
down_revision: Union[str, None] = '78a699ac423d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ai_documents_task_id'), 'ai_documents', ['task_id'], unique=False)
    op.create_index(op.f('ix_pipeline_steps_pipeline_run_id'), 'pipeline_steps', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_task_files_task_id'), 'task_files', ['task_id'], unique=False)
    op.create_index(op.f('ix_transcripts_task_id'), 'transcripts', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcripts_task_id'), table_name='transcripts')
    op.drop_index(op.f('ix_task_files_task_id'), table_name='task_files')
    op.drop_index(op.f('ix_pipeline_steps_pipeline_run_id'), table_name='pipeline_steps')
    op.drop_index(op.f('ix_ai_documents_task_id'), table_name='ai_documents')
    # ### end Alembic commands ###
