"""add_last_login_to_users

Revision ID: e841e271fb65
Revises: c481f8f17fde
Create Date: 2026-07-09 19:34:39.203283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e841e271fb65'
down_revision: Union[str, None] = 'c481f8f17fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcripts', 'format_profile')
    op.drop_column('transcripts', 'speech_blocks')
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    op.add_column('transcripts', sa.Column('speech_blocks', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('transcripts', sa.Column('format_profile', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
